name: Backport merged pull request

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: 'Backport pull request'
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v3
        with:
          label_pattern: '^Backport ([^ ]+)$'
          github_token: ${{ secrets.BACKPORT_TOKEN }}
